#应用程序端口配置
server: 
  port: 30001
#  tomcat:
#    access-log-enabled: true

spring:
  application:
    name: springboot-rabbitmq
  rabbitmq:
    host: 192.168.1.182
    port: 5672
    username: stt
    password: 123456
    publisher-confirms: true
    virtual-host: /