#应用程序端口配置
server:
  port: 30003
#  tomcat:
#    access-log-enabled: true

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 192.168.1.252:22122
  pool:
    #从池中借出的对象的最大数目
    maxTotal: 153
    #获取连接时的最大等待毫秒数100
    maxWaitMillis: 102

spring:
  jmx:
    enabled: false
  #文件上传大小配置
  http:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB
